---
- name: Create configuration for leaf devices
  hosts: leaf
  connection: local
  gather_facts: no
  roles:
    - junos-system
    - junos-ebgp
    - junos-access
    - junos-rpm
    - build-config
